### ISSUE TITLE
Weights.bin model.json are repeated loaded

### ISSUE THREAD

**Issue by tangmingsh** [manfye/react-tfjs-azure-objDetect#1]
@manfye ,
I fllow your  tutorial to run the app, but when start detect I could not see the predict result.
Here are the debug info of console.
Weights.bin model.json are repeated loaded.

![](https://www.sjaiedu.com/imgs/2022-03-18_064809.jpg)
![](https://www.sjaiedu.com/imgs/2022-03-18_063240.jpg)

**Comment by manfye** [comment]
@tangmingsh it might due to your useeffect functionality. make sure it is only trigger once
